/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.interfaz;

/**
 *
 * @author Lenovo
 */
public class FrmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistro
     */
    public FrmRegistro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUseradd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nuevoUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1SalirNuevoUser = new javax.swing.JButton();
        nuevacontraseña = new javax.swing.JPasswordField();
        regresar = new javax.swing.JButton();
        FondoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUseradd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/interfaz/user.png"))); // NOI18N
        getContentPane().add(labelUseradd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 280));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 30));
        getContentPane().add(nuevoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 220, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 140, 40));

        jButton1SalirNuevoUser.setBackground(new java.awt.Color(255, 102, 0));
        jButton1SalirNuevoUser.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jButton1SalirNuevoUser.setText("Salir");
        jButton1SalirNuevoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalirNuevoUserActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1SalirNuevoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, 30));
        getContentPane().add(nuevacontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 220, 30));

        regresar.setBackground(new java.awt.Color(255, 102, 0));
        regresar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        FondoRegistro.setBackground(new java.awt.Color(255, 153, 51));
        FondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/interfaz/FONDO-NARANJA.png"))); // NOI18N
        getContentPane().add(FondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 508, 281));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SalirNuevoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalirNuevoUserActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1SalirNuevoUserActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        Tent tent = new Tent();
        tent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoRegistro;
    private javax.swing.JButton jButton1SalirNuevoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelUseradd;
    private javax.swing.JPasswordField nuevacontraseña;
    private javax.swing.JTextField nuevoUser;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
